let modeloJson = [
    {
      id: 1,
      name: 'Câmera Instax Mini 9',
      img: 'img/cam1.png',
      price: 380.00,
      sizes: ['Preta', '(imagem)', 'Preta'],
      description: 'Cãmera instantânea Fujifilm-Azul bebê',
    },
    {
      id: 2,
      name: 'Câmera polaroid',
      img: 'img/cam2.png',
      price: 600.00,
      sizes: ['Preta', '(imagem)', 'Preta'],
      description: 'Câmera Polaroid fotográfica - Instantânea',
    },
    {
      id: 3,
      name: 'Câmera Canon',
      img: 'img/cam3.png',
      price: 500.00,
      sizes: ['Preta', '(imagem)', 'Preta'],
      description: 'Câmera digital Canon',
    },
    {
      id: 4,
      name: 'Câmera Olympus-pen',
      img: 'img/cam4.png',
      price: 200.00,
      sizes: ['Preta', '(imagem)', 'Preta'],
      description: 'Câmera retro modelo antigo Olympus-pen',
    },
    {
      id: 5,
      name: 'Câmera modelo antigo',
      img: 'img/cam5.png',
      price: 150.00,
      sizes: ['Preta', '(imagem)', 'Preta'],
      description: 'Câmera modelo antigo - vibe vintage',
    },
    {
      id: 6,
      name: 'Câmera Sony',
      img: 'img/cam6.png',
      price: 850.00,
      sizes: ['Preta', '(imagem)', 'Preta'],
      description: 'Câmera digital sony - portatil',
    },
    {
      id: 7,
      name: 'Câmera modelo antigo-ALPA',
      img: 'img/cam7.png',
      price: 250.00,
      sizes: ['Preta', '(imagem)', 'Preta'],
      description: 'Câmera antiga retro - fácil manuseio',
    },

    {
        id: 8,
        name: 'Câmera Sony',
        img: 'img/cam8.png',
        price: 400.00,
        sizes: ['Preta', '(imagem)', 'Preta'],
        description: 'Câmera Digital Sony - pequena e portatil cor preta',
      },

    {
        id: 9,
        name: 'Câmera Instax Mini 11',
        img: 'img/cam9.png',
        price: 450.00,
        sizes: ['Preta', '(imagem)', 'Preta'],  /* sizes: ['malha', 'dry', 'dry'], */
        description: 'Câmera Instantânea - Mini 11 Preta',
      },  
  ];